[build]
command = "apt-get update && apt-get install -y cmake libgl1 libglib2.0-0 g++ make && pip install -r requirements.txt"

[start]
command = "streamlit run Home.py --server.port=${PORT} --server.address=0.0.0.0"
